apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka-namespace
spec:
  kafka:
    version: "3.4.0"
    replicas: 3
    listeners:
      oauth:
        authentication:
          type: oauth
      plain: {}
      tls:
        authentication:
          type: tls
    config:
      oauth.token.endpoint.uri: "https://auth-server.com/oauth/token"
      oauth.client.id: "your-client-id"
      oauth.client.secret: "your-client-secret"
    storage:
      type: persistent-claim
      size: 5Gi
      class: standard
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      class: standard
