apiVersion: v1  # Xác định phiên bản API mà bạn đang sử dụng cho Secret. "v1" là phiên bản ổn định.
kind: Secret  # Loại tài nguyên, ở đây là Secret, dùng để lưu trữ thông tin nhạy cảm như mật khẩu.
metadata:  # Phần metadata chứa thông tin về Secret.
  name: k8s-demo-secret  # Tên của Secret.
type: Opaque  # Loại Secret, "Opaque" là loại chung cho dữ liệu nhạy cảm.
data:  # Dữ liệu được mã hóa mà Secret sẽ lưu trữ.
  #abCD@1234 mã hóa base 64 : echo -n 'abCD@1234' | base64
  db-password: LW4gJ2FiQ0RAMTIzNCcgDQo=  # Mật khẩu của cơ sở dữ liệu được mã hóa bằng Base64.
