apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: popef23/service-a:latest
      ports:
        - containerPort: 8831
  imagePullSecrets:
    - name: my-registry-secret
