apiVersion: apps/v1  # Định nghĩa phiên bản API cho Deployment
kind: Deployment  # Loại tài nguyên là Deployment
metadata:
  name: test-deployment  # Tên của Deployment
spec:
  replicas: 1  # Số lượng bản sao của ứng dụng
  selector:
    matchLabels:
      app: test-app  # Nhãn để xác định Pod
  template:
    metadata:
      labels:
        app: test-app  # Nhãn cho Pod
    spec:
      containers:
        - name: container-a  # Tên container
          image: popef23/service-a:latest  # Hình ảnh Docker để pull
      imagePullSecrets:  # Chỉ định secret để pull image
        - name: my-registry-secret  # Tên secret
