apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv # tên truy cập
  labels:
    type: local  # nhãn phân loại
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"