spring:
  application:
    name: service_a
  kafka:
    bootstrap-servers: localhost:9092

    # Cấu hình Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-512
        #jaas là file cấu hình đăng ký giao tiếp với kafka broker
        sasl.jaas.config: |
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="producer_a_service"
          password="abCD@1234";

    # Cấu hình Consumer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: b-group
      properties:
        security.protocol: SASL_PLAINTEXT
        ssl.truststore.location: classpath:ssl/kafka.client.truststore.jks
        ssl.truststore.password: abCD@
        ssl.keystore.location: classpath:ssl/kafka.client.keystore.jks
        ssl.keystore.password: abCD@
        ssl.key.password: abCD@
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: |
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="consumer_a_service"
          password="abCD@12";
logging:
  level:
    org.apache.kafka.common.security.scram.ScramLoginModule: DEBUG
    org.apache.kafka.common.security.authenticator: DEBUG
    org.apache.kafka.common.security.ssl: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG

  # Cấu hình Bảo mật OAuth2 (nếu cần)
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://your-auth-server.com/
#          jwk-set-uri: https://your-auth-server.com/.well-known/jwks.json
#          audiences: https://my-resource-server.example.com
#          jws-algorithms: RS512
#          public-key-location: classpath:my-key.pub
server:
  port: 8881
